name: LocalGGUFChat
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '15.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    PRODUCT_BUNDLE_IDENTIFIER: com.example.LocalGGUFChat

packages:
  SwiftLlama:
    url: https://github.com/ShenghaiWang/SwiftLlama.git
    from: 0.4.0

targets:
  LocalGGUFChat:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: LocalGGUFChat
    resources:
      - path: LocalGGUFChat/Resources
    settings:
      base:
        INFOPLIST_FILE: LocalGGUFChat/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        ENABLE_BITCODE: NO
    dependencies:
      - package: SwiftLlama
