name: LocalGGUFChat

options:
  deploymentTarget:
    iOS: "18.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.LocalGGUFChat
    SWIFT_VERSION: "5.0"

packages:
  SwiftLlama:
    url: https://github.com/ShenghaiWang/SwiftLlama.git
    from: 0.4.0

targets:
  LocalGGUFChat:
    type: application
    platform: iOS
    sources:
      - path: LocalGGUFChat
    resources:
      - path: LocalGGUFChat/Resources
    dependencies:
      - package: SwiftLlama
