name: LocalGGUFChat
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"

packages:
  SwiftLlama:
    url: https://github.com/ShenghaiWang/SwiftLlama.git
    from: 0.4.0

targets:
  LocalGGUFChat:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: LocalGGUFChat
        excludes:
          - "**/*.md"
    resources:
      - path: LocalGGUFChat/Resources
    info:
      path: LocalGGUFChat/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.LocalGGUFChat
        SWIFT_VERSION: "5.0"
    dependencies:
      - package: SwiftLlama
